language: node_js
node_js:
  - '10'

sudo: false
dist: xenial

addons:
  apt:
    packages:
      - libgconf-2-4

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

cache:
  yarn: true
  directories:
    # we also need to cache folder with Cypress binary
    - ~/.cache

install:
  - yarn install --ignore-engines

stages:
  - test
  - name: npm-release
    if: (tag =~ ^v)
  - name: github-releases
    if: (tag =~ ^v)

jobs:
  include:
    - stage: test
      script:
        - yarn test
    - stage: npm-release
      script:
        - yarn build
      # Identifies `a.b.c-xxx.n` tags as pre-releases, and `a.b.c` as stable releases
      before_deploy: |
        function npm_dist_tag() {
          if [[ "$TRAVIS_TAG" = *"-"* ]]; then
            echo "next"
          else
            echo "latest"
          fi
        }
      deploy:
        provider: npm
        tag: $(npm_dist_tag)
        email: rwwagner90@gmail.com
        skip_cleanup: true
        api_key:
          secure: "Cd1paqDwt2tNcFYudn9lcnVl/wV9DAG9E5YlnbuoXzrFaK3AA8htlblGLYVij0kf4/1mo3ftsLKtoSCM45fWjSPEsZpsjGq0Sx8r6hg/ICkBkQHhm0dKpFy8245sYhEDfiu1jHV5556OUtZ7iNeH1zQ5Vy1t8VwJLJuGw/jrtOw="
        on:
          branch: master
          tags: true
          repo: shipshapecode/tether
        after_deploy: |
          if [ "$(npm_dist_tag)" == "latest" ]; then
            npm dist-tag rm tether next || true
          fi
    - stage: github-releases
      script:
        - yarn build
      # Identifies `a.b.c-xxx.n` tags as pre-releases, and `a.b.c` as stable releases
      before_deploy: |
        function gh_prerelease() {
          if [[ "$TRAVIS_TAG" = *"-"* ]]; then
            echo true
          else
            echo false
          fi
        }
      deploy:
        provider: releases
        api_key:
          secure: "jF72DkLlXj1P6Ro8zJyGKKtEWsJEPrBdh4TOlP//Vbw0kTXH63H7WjRXRSUE1JEZoAWnf6JgJRsJFY2WbEilnnns55p3CHS/gjCFZvpDOKZN4iQ+AgFJn3oC2WTdaBtqMQH72v6PKNV686V3uFOqhGP/Ze6cpTIAISyBwc6Yfyg="
        file_glob: true
        file:
          - dist/css/*
          - dist/js/*
        skip_cleanup: true
        prerelease: $(gh_prerelease)
        on:
          tags: true

